 groups:
   - name: alert.rules
     rules:
     - alert: InstanceDown
       expr: up == 0 # любое PromQL выражение
       for: 1m # В течении какого времени, по умолчанию 0
       labels: # Дополнительные метки
         severity: page
       annotations:
         description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
         summary: 'Instance {{ $labels.instance }} down'


